name: lista_de_contatos
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite:
  path_provider:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
